# Generated by Django 2.2.28 on 2026-06-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangMansApp', '0005_secure_game_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
    ]
